routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TimesheetController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Route::post('api/fetch-states', [DropdownController::class, 'fetchState']);
Route::post('api/fetch-cities', [DropdownController::class, 'fetchCity']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'customers'], function () {
        Route::resource('customers', CustomerController::class);
        Route::resource('contacts', ContactController::class);
        Route::resource('locations', LocationController::class);
    });
    Route::group(['prefix' => 'projects'], function () {
        Route::resource('projects', ProjectController::class);
        Route::resource('timesheets', TimesheetController::class);
        Route::resource('invoices', InvoiceController::class);
    });
});

require __DIR__ . '/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Project extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'name',
        'description',
        'price_hour',
        'price_day',
        'price_fix',
        'started_at',
        'ended_at',
        'customer_id',
    ];

    protected $searchableFields = ['*'];

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    public function timesheets(): HasMany
    {
        return $this->hasMany(Timesheet::class);
    }

    public function setPriceHourAttribute($price): void
    {
        $this->attributes['price_hour'] = $price * 100;
    }

    public function setPriceDayAttribute($price): void
    {
        $this->attributes['price_day'] = $price * 100;
    }

    public function setPriceFixAttribute($price): void
    {
        $this->attributes['price_fix'] = $price * 100;
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Project\StoreRequest;
use App\Http\Requests\Project\UpdateRequest;
use App\Models\Customer;
use App\Models\Project;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ProjectController extends Controller
{
    public function index(Request $request): View
    {
        $search = $request->get('search', '');

        $projects = Project::search($search)
            ->latest()
            ->withCount('timesheets')
            ->with('customer:id,name')
            ->paginate(10);

        return view('projects.index', compact('projects', 'search'));
    }

    public function create(): View
    {
        $customers = Customer::pluck('name', 'id');

        return view('projects.create', compact('customers'));
    }

    public function store(StoreRequest $request): RedirectResponse
    {
        Project::create($request->validated());

        return redirect()
            ->route('projects.index')
            ->withSuccess('Project has been created successfully.');
    }

    public function show(Project $project): View
    {
        return view('projects.show', compact('project'));
    }

    public function edit(Project $project): View
    {
        $customers = Customer::pluck('name', 'id');

        return view('projects.edit', compact('customers', 'project'));
    }

    public function update(Project $project, UpdateRequest $request): RedirectResponse
    {
        $project->update($request->validated());

        return redirect()
            ->route('projects.index')
            ->withSuccess('Project Has Been updated successfully');
    }

    public function destroy(Project $project): RedirectResponse
    {
        $project->delete();

        return redirect()
            ->route('projects.index')
            ->withSuccess('Project has been deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/FormatAmount.php
<?php

namespace App\View\Components;

use Illuminate\Support\Str;
use Illuminate\View\Component;
use Money\Currencies\ISOCurrencies;
use Money\Currency;
use Money\Formatter\IntlMoneyFormatter;
use Money\Money;
use NumberFormatter;

class FormatAmount extends Component
{
    private $amount;
    private $currency;
    private $locale;

    public function __construct(int $amount, string $currency, ?string $locale = null)
    {
        $this->amount = $amount;
        $this->currency = $currency;
        $this->locale = $locale ?? app()->getLocale();
    }

    public function render()
    {
        $money = new Money($this->amount, new Currency(Str::upper($this->currency)));

        $numberFormatter = new NumberFormatter($this->locale, NumberFormatter::CURRENCY);
        $moneyFormatter = new IntlMoneyFormatter($numberFormatter, new ISOCurrencies());

        return $moneyFormatter->format($money);
    }
}

resources/views/projects/create.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Create project') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('projects.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form action="{{ route('projects.store') }}" method="POST" >
                    @csrf
                    <div class="mb-4">
                        <x-label for="customer_id" :value="__('project.customer')" class="required" />

                        <select name="customer_id" id="customer_id" 
                        class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required>
                            <option disabled hidden {{ old('customer_id') != null ?: 'selected' }}>
                                {{ __('project.select') }}
                            </option>
                            @foreach($customers as $value => $label)
                                <option value="{{ $value }}" {{ old('customer_id') != $value ?: 'selected' }}>
                                    {{ $label }}
                                </option>
                            @endforeach
                        </select>
                    </div>    
                    <div class="mb-4">
                        <x-label for="name" :value="__('project.name')" class="required" />

                        <x-input id="name" class="block mt-1 w-full"
                        type="text"
                        name="name"
                        value="{{ old('name') }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="description" :value="__('project.description')" />

                        <textarea id="description" name="description" class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                            {{ old('description') }}
                        </textarea>
                    </div>
                    <div class="mb-4">
                        <x-label for="price_hour" :value="__('project.price_hour')" class="required" />

                        <x-input id="price_hour" class="block mt-1 w-full"
                        type="number"
                        name="price_hour"
                        step="0.01" min="0" max="100"
                        value="{{ old('price_hour') }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="price_day" :value="__('project.price_day')" class="required" />

                        <x-input id="price_day" class="block mt-1 w-full"
                        type="number"
                        name="price_day"
                        step="0.01" min="0" max="1000"
                        value="{{ old('price_day') }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="price_fix" :value="__('project.price_fix')" />

                        <x-input id="price_fix" class="block mt-1 w-full"
                        type="number"
                        name="price_fix"
                        step="0.01" min="0" max="100000"
                        value="{{ old('price_fix') }}" />
                    </div>
                    <div class="mb-4">
                        <x-label for="started_at" :value="__('project.started_at')" />

                        <x-input id="started_at" class="block mt-1 w-full"
                        type="date"
                        name="started_at"
                        value="{{ old('started_at') }}" />
                    </div>
                    <div class="mb-4">
                        <x-label for="ended_at" :value="__('project.ended_at')" />

                        <x-input id="ended_at" class="block mt-1 w-full"
                        type="date"
                        name="ended_at"
                        value="{{ old('ended_at') }}" />
                    </div>
                    <div>
                        <x-button>{{ __('customer.submit') }}</x-button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/projects/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Edit Project') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('projects.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form action="{{ route('projects.update', $project) }}" method="POST">
                    @csrf
                    @method('PUT')

                    <div class="mb-4">
                        <x-label for="customer_id" :value="__('project.customer')" class="required" />

                        <select name="customer_id" id="customer_id" 
                        class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required>
                            <option disabled hidden {{ old('customer_id', $project->customer->id) }}!= null ?: 'selected' }}>
                                {{ __('project.select') }}
                            </option>
                            @foreach($customers as $value => $label)
                                <option value="{{ $value }}" {{ old('customer_id', $project->customer->id) != $value ?: 'selected' }}>
                                    {{ $label }}
                                </option>
                            @endforeach
                        </select>
                    </div>    
                    <div class="mb-4">
                        <x-label for="name" :value="__('project.name')" class="required" />

                        <x-input id="name" class="block mt-1 w-full"
                        type="text"
                        name="name"
                        value="{{ old('name', $project->name) }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="description" :value="__('project.description')" />

                        <textarea id="description" name="description" class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                            {{ old('description', $project->description) }}
                        </textarea>
                    </div>
                    <div class="mb-4">
                        <x-label for="price_hour" :value="__('project.price_hour')" class="required" />

                        <x-input id="price_hour" class="block mt-1 w-full"
                        type="number"
                        name="price_hour"
                        step="0.01" min="0" max="100"
                        value="{{ old('price_hour', $project->price_hour) }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="price_day" :value="__('project.price_day')" class="required" />

                        <x-input id="price_day" class="block mt-1 w-full"
                        type="number"
                        name="price_day"
                        step="0.01" min="0" max="1000"
                        value="{{ old('price_day', $project->price_day) }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="price_fix" :value="__('project.price_fix')" />

                        <x-input id="price_fix" class="block mt-1 w-full"
                        type="number"
                        name="price_fix"
                        step="0.01" min="0" max="100000"
                        value="{{ old('price_fix', $project->price_fix) }}" />
                    </div>
                    <div class="mb-4">
                        <x-label for="started_at" :value="__('project.started_at')" />

                        <x-input id="started_at" class="block mt-1 w-full"
                        type="date"
                        name="started_at"
                        value="{{ old('started_at', $project->started_at) }}" />
                    </div>
                    <div class="mb-4">
                        <x-label for="ended_at" :value="__('project.ended_at')" />

                        <x-input id="ended_at" class="block mt-1 w-full"
                        type="date"
                        name="ended_at"
                        value="{{ old('ended_at', $project->ended_at) }}" />
                    </div>
                    <div>
                        <x-button>{{ __('customer.submit') }}</x-button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/projects/index.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Project list') }}
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <div class="mb-5 mt-4">
                    <div class="flex flex-wrap justify-between">
                        <div class="md:w-1/2">
                            <x-table-search :search="$search"/>
                        </div>
                        <div class="md:w-1/2 text-right">
                            <x-table-create model="projects" />
                        </div>
                    </div>
                    <x-table-error />
                </div>
                <x-table>
                    <x-slot name="header">
                        <x-table-column>{{ __('Customer') }}</x-table-column>
                        <x-table-column>{{ __('Name') }}</x-table-column>
                        <x-table-column>{{ __('Price hour') }}</x-table-column>
                        <x-table-column>{{ __('Price day') }}</x-table-column>
                        <x-table-column>{{ __('Price fix') }}</x-table-column>
                        <x-table-column>{{ __('Started at') }}</x-table-column>
                        <x-table-column>{{ __('Ended at') }}</x-table-column>
                        <x-table-column>{{ __('Timesheets') }}</x-table-column>
                        <x-table-column>{{ __('Action') }}</x-table-column>
                    </x-slot>
                    @forelse($projects as $row)
                        <tr>
                            <x-table-column><a href="{{ route('customers.show',$row->customer) }}" class="hover:underline">{{ $row->customer->name }}</a></x-table-column>
                            <x-table-column>{{ $row->name }}</x-table-column>
                            <x-table-column><x-format-amount :amount="$row->price_hour" currency="eur" locale="fr_BE" /></x-table-column>
                            <x-table-column><x-format-amount :amount="$row->price_day" currency="eur" locale="fr_BE" /></x-table-column>
                            <x-table-column><x-format-amount :amount="$row->price_fix" currency="eur" locale="fr_BE" /></x-table-column>
                            <x-table-column>{{ $row->started_at ?? '-' }}</x-table-column>
                            <x-table-column>{{ $row->ended_at ?? '-' }}</x-table-column>
                            <x-table-column><a href="{{ route('timesheets.index',['search'=>$row->id]) }}"><span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-200 dark:text-green-900">{{ $row->timesheets_count }}</span></a></x-table-column>
                            <x-table-column>
                                <x-table-action model="projects" :row="$row"/>
                            </x-table-column>
                        </tr>
                    @empty
                        <tr>
                            <td class="px-4 py-2 border text-red-500" colspan="9">{{ __('No project found.') }}</td>
                        </tr>
                    @endforelse
                    <x-slot name="pagination">
                        {{ $projects->links() }}    
                    </x-slot>
                </x-table>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/projects/show.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Show Project') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('projects.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <table class="w-full table-fixed">
                    <tbody>
                        <tr>
                            <td class="px-4 py-2 font-bold">Company</td>
                            <td>{{ $project->customer->name }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Name</td>
                            <td>{{ $project->name }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Price hour</td>
                            <td>{{ $project->price_hour }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Price day</td>
                            <td>{{ $project->price_day }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Price fix</td>
                            <td>{{ $project->price_fix }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Started at</td>
                            <td>{{ $project->started_at }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Ended at</td>
                            <td>{{ $project->ended_at }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Created on</td>
                            <td>{{ date_format($project->created_at, 'jS F Y g:i A') }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Last updated</td>
                            <td>{{ date_format($project->updated_at, 'jS F Y g:i A') }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>