routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TimesheetController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Route::post('api/fetch-states', [DropdownController::class, 'fetchState']);
Route::post('api/fetch-cities', [DropdownController::class, 'fetchCity']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'customers'], function () {
        Route::resource('customers', CustomerController::class);
        Route::resource('contacts', ContactController::class);
        Route::resource('locations', LocationController::class);
    });
    Route::group(['prefix' => 'projects'], function () {
        Route::resource('projects', ProjectController::class);
        Route::resource('timesheets', TimesheetController::class);
        Route::resource('invoices', InvoiceController::class);
    });
});

require __DIR__ . '/auth.php';

app/Models/Customer.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Customer extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['name', 'vat'];

    protected $guarded = [];

    protected $searchableFields = ['*'];

    public function contacts(): HasMany
    {
        return $this->hasMany(Contact::class);
    }

    public function locations(): HasMany
    {
        return $this->hasMany(Location::class);
    }

    public function projects(): HasMany
    {
        return $this->hasMany(Project::class);
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Customer\StoreRequest;
use App\Http\Requests\Customer\UpdateRequest;
use App\Models\Customer;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class CustomerController extends Controller
{
    public function index(Request $request): View
    {
        $search = $request->get('search', '');

        $customers = Customer::search($search)
            ->latest()
            ->withCount('contacts')
            ->withCount('locations')
            ->withCount('projects')
            ->paginate(10);

        return view('customers.index', compact('customers', 'search'));
    }

    public function create(): View
    {
        return view('customers.create');
    }

    public function store(StoreRequest $request): RedirectResponse
    {
        Customer::create($request->validated());

        return redirect()
            ->route('customers.index')
            ->withSuccess('Customer has been created successfully.');
    }

    public function show(Customer $customer): View
    {
        return view('customers.show', compact('customer'));
    }

    public function edit(Customer $customer): View
    {
        return view('customers.edit', compact('customer'));
    }

    public function update(Customer $customer, UpdateRequest $request): RedirectResponse
    {
        $customer->update($request->validated());

        return redirect()
            ->route('customers.index')
            ->withSuccess('CUstomer Has Been updated successfully');
    }

    public function destroy(Customer $customer): RedirectResponse
    {
        $customer->delete();

        return redirect()
            ->route('customers.index')
            ->withSuccess('Customer has been deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/customers/create.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Create Customer') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('customers.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form action="{{ route('customers.store') }}" method="POST" >
                    @csrf
                <div class="mb-4">
                    <x-label for="name" :value="__('customer.name')" class="required" />

                    <x-input id="name" class="block mt-1 w-full"
                    type="text"
                    name="name"
                    value="{{ old('name') }}"
                    required />
                </div>
                <div class="mb-4">
                    <x-label for="vat" :value="__('customer.vat')" class="required" />
                    <x-input id="vat" class="block mt-1 w-full"
                    type="text"
                    name="vat"
                    value="{{ old('vat') }}"
                    required />
                </div>
                <div>
                    <x-button>{{ __('customer.submit') }}</x-button>
                </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/customers/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Edit Customer') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('customers.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form action="{{ route('customers.update', $customer) }}" method="POST">
                    @csrf
                    @method('PUT')
                <div class="mb-4">
                    <x-label for="name" :value="__('customer.name')" class="required" />

                    <x-input id="name" class="block mt-1 w-full"
                        type="text"
                        name="name"
                        value="{{ old('name', $customer->name) }}"
                        required />
                </div>
                <div class="mb-4">
                    <x-label for="vat" :value="__('customer.vat')" class="required" />

                    <x-input id="vat" class="block mt-1 w-full"
                        type="text"
                        name="vat"
                        value="{{ old('vat', $customer->vat) }}"
                        required />
                </div>
                <div>
                    <x-button>{{ __('customer.submit') }}</x-button>
                </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/customers/index.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Customer list') }}
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <div class="mb-5 mt-4">
                    <div class="flex flex-wrap justify-between">
                        <div class="md:w-1/2">
                            <x-table-search :search="$search"/>
                        </div>
                        <div class="md:w-1/2 text-right">
                            <x-table-create model="customers" />
                        </div>
                    </div>
                    <x-table-error />
                </div>
                <x-table>
                    <x-slot name="header">
                        <x-table-column>{{ __('Name') }}</x-table-column>
                        <x-table-column>{{ __('VAT') }}</x-table-column>
                        <x-table-column>{{ __('Contacts') }}</x-table-column>
                        <x-table-column>{{ __('Locations') }}</x-table-column>
                        <x-table-column>{{ __('Projects') }}</x-table-column>
                        <x-table-column>{{ __('Action') }}</x-table-column>
                    </x-slot>
                    @forelse($customers as $row)
                        <tr>
                            <x-table-column>{{ $row->name ?? '-' }}</x-table-column>
                            <x-table-column>{{ $row->vat ?? '-' }}</x-table-column>
                            <x-table-column><a href="{{ route('contacts.index',['search'=>$row->id]) }}"><span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-200 dark:text-green-900">{{ $row->contacts_count }}</span></a></x-table-column>
                            <x-table-column><a href="{{ route('locations.index',['search'=>$row->id]) }}"><span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-200 dark:text-green-900">{{ $row->locations_count }}</span></a></x-table-column>
                            <x-table-column><a href="{{ route('projects.index',['search'=>$row->id]) }}"><span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-200 dark:text-green-900">{{ $row->projects_count }}</span></a></x-table-column>
                            <x-table-column>
                                <x-table-action model="customers" :row="$row"/>
                            </x-table-column>
                        </tr>
                    @empty 
                        <tr>
                            <td class="px-4 py-2 border text-red-500" colspan="6">{{ __('No contact found.') }}<</td>
                        </tr>
                    @endforelse
                    <x-slot name="pagination">
                        {{ $customers->links() }}
                    </x-slot>
                </x-table>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/customers/show.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Show Customer') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('customers.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <table class="w-full table-fixed">
                    <tbody>
                        <tr>
                            <td class="px-4 py-2 font-bold">Name</td>
                            <td>{{ $customer->name }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">VAT</td>
                            <td>{{ $customer->vat }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Created on</td>
                            <td>{{ date_format($customer->created_at, 'jS F Y g:i A') }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Last updated</td>
                            <td>{{ date_format($customer->updated_at, 'jS F Y g:i A') }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>