routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TimesheetController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Route::post('api/fetch-states', [DropdownController::class, 'fetchState']);
Route::post('api/fetch-cities', [DropdownController::class, 'fetchCity']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'customers'], function () {
        Route::resource('customers', CustomerController::class);
        Route::resource('contacts', ContactController::class);
        Route::resource('locations', LocationController::class);
    });
    Route::group(['prefix' => 'projects'], function () {
        Route::resource('projects', ProjectController::class);
        Route::resource('timesheets', TimesheetController::class);
        Route::resource('invoices', InvoiceController::class);
    });
});

require __DIR__ . '/auth.php';

app/Models/Timesheet.php
<?php

namespace App\Models;

use App\Enums\PriceTypeEnum;
use App\Models\Scopes\Searchable;
use App\Services\Timesheet as ServicesTimesheet;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Timesheet extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['description', 'price_type', 'started_at', 'ended_at', 'project_id', 'invoice_id'];

    protected $casts = ['price_type' => PriceTypeEnum::class, 'started_at' => 'datetime', 'ended_at' => 'datetime'];

    protected $searchableFields = ['*'];

    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function invoice(): BelongsTo
    {
        return $this->belongsTo(Invoice::class);
    }

    public function getPriceAttribute(): int
    {
        $timesheetService = new ServicesTimesheet();
        return $timesheetService->calculateTimeSheetPrice($this) * 100;
    }
}

app/Http/Controllers/TimesheetController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Timesheet\StoreRequest;
use App\Http\Requests\Timesheet\UpdateRequest;
use App\Models\Project;
use App\Models\Timesheet;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class TimesheetController extends Controller
{
    public function index(Request $request): View
    {
        $search = $request->get('search', '');

        $timesheets = Timesheet::search($search)
            ->latest()
            ->with('project:id,name')
            ->with('project.customer')
            ->with('invoice')
            ->paginate(10);

        return view('timesheets.index', compact('timesheets', 'search'));
    }

    public function create(): View
    {
        $projects = Project::with('customer')->get();

        return view('timesheets.create', compact('projects'));
    }

    public function store(StoreRequest $request): RedirectResponse
    {
        Timesheet::create($request->validated());

        return redirect()
            ->route('timesheets.index')
            ->withSuccess('Timesheet has been created successfully.');
    }

    public function show(Timesheet $timesheet): View
    {
        return view('timesheets.show', compact('timesheet'));
    }

    public function edit(Timesheet $timesheet): View
    {
        $projects = Project::with('customer')->get();

        return view('timesheets.edit', compact('timesheet', 'projects'));
    }

    public function update(Timesheet $timesheet, UpdateRequest $request): RedirectResponse
    {
        $timesheet->update($request->validated());

        return redirect()
            ->route('timesheets.index')
            ->withSuccess('Timesheet Has Been updated successfully');
    }

    public function destroy(Timesheet $timesheet): RedirectResponse
    {
        $timesheet->delete();

        return redirect()
            ->route('timesheets.index')
            ->withSuccess('Timesheet has been deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/FormatAmount.php
<?php

namespace App\View\Components;

use Illuminate\Support\Str;
use Illuminate\View\Component;
use Money\Currencies\ISOCurrencies;
use Money\Currency;
use Money\Formatter\IntlMoneyFormatter;
use Money\Money;
use NumberFormatter;

class FormatAmount extends Component
{
    private $amount;
    private $currency;
    private $locale;

    public function __construct(int $amount, string $currency, ?string $locale = null)
    {
        $this->amount = $amount;
        $this->currency = $currency;
        $this->locale = $locale ?? app()->getLocale();
    }

    public function render()
    {
        $money = new Money($this->amount, new Currency(Str::upper($this->currency)));

        $numberFormatter = new NumberFormatter($this->locale, NumberFormatter::CURRENCY);
        $moneyFormatter = new IntlMoneyFormatter($numberFormatter, new ISOCurrencies());

        return $moneyFormatter->format($money);
    }
}

resources/views/timesheets/create.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Create timesheet') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('timesheets.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form action="{{ route('timesheets.store') }}" method="POST" >
                    @csrf
                    <div class="mb-4">
                        <x-label for="project_id" :value="__('timesheet.project')" class="required" />
                        <select class="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                        name="project_id">
                            @foreach($projects as $value => $label)
                                <option value="{{ $value }}" {{ old('project_id') != $value ?: 'selected' }}>
                                    {{ $label->name }} ({{ $label->customer->name }})
                                </option>
                            @endforeach
                        </select>
                    </div>    
                    <div class="mb-4">
                        <x-label for="description" :value="__('timesheet.description')" class="required" />

                        <x-input id="description" class="block mt-1 w-full"
                        type="text"
                        name="description"
                        value="{{ old('description') }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="price_type" :value="__('timesheet.price_type')" class="required" />
                        <select class="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                        name="price_type">
                            @foreach(App\Enums\PriceTypeEnum::cases() as $priceType)
                                <option value="{{ $priceType->value }}" {{ old('price_type') != $priceType->value ?: 'selected' }}>
                                    {{ $priceType->name }}
                                </option>
                            @endforeach
                        </select>
                        @error('price_type') <span class="text-red-500">{{ $message }}
                        </span>@enderror
                    </div>
                    <div class="mb-4">
                        <x-label for="started_at" :value="__('timesheet.started_at')" class="required" />

                        <x-input id="started_at" class="block mt-1 w-full"
                        type="datetime-local"
                        name="started_at"
                        value="{{ old('started_at') }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="ended_at" :value="__('timesheet.ended_at')" />

                        <x-input id="ended_at" class="block mt-1 w-full"
                        type="datetime-local"
                        name="ended_at"
                        value="{{ old('ended_at') }}" />
                    </div>
                    <div>
                        <x-button>{{ __('customer.submit') }}</x-button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/timesheets/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Edit Timesheet') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('timesheets.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form action="{{ route('timesheets.update', $timesheet) }}" method="POST">
                    @csrf
                    @method('PUT')

                    <div class="mb-4">
                        <x-label for="project_id" :value="__('timesheet.project')" class="required" />
                        <select class="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                        name="project_id">
                            @foreach($projects as $value => $label)
                                <option value="{{ $value }}" {{ old('project_id', $timesheet->project->id) != $value ?: 'selected' }}>
                                    {{ $label->name }} ({{ $label->customer->name }})
                                </option>
                            @endforeach
                        </select>
                    </div>    
                    <div class="mb-4">
                        <x-label for="description" :value="__('timesheet.description')" class="required" />

                        <x-input id="description" class="block mt-1 w-full"
                        type="text"
                        name="description"
                        value="{{ old('description', $timesheet->description) }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="price_type" :value="__('timesheet.price_type')" class="required" />
                        <select class="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
                        name="price_type">
                            @foreach(App\Enums\PriceTypeEnum::cases() as $priceType)
                                <option value="{{ $priceType->value }}" {{ old('price_type', $timesheet->price_type) != $priceType->value ?: 'selected' }}>
                                    {{ $priceType->name }}
                                </option>
                            @endforeach
                        </select>
                        @error('price_type') <span class="text-red-500">{{ $message }}
                        </span>@enderror
                    </div>
                    <div class="mb-4">
                        <x-label for="started_at" :value="__('timesheet.started_at')" class="required" />

                        <x-input id="started_at" class="block mt-1 w-full"
                        type="dateTime-local"
                        name="started_at"
                        value="{{ old('started_at', date('Y-m-d\TH:m:s',  strtotime($timesheet->started_at))) }}"
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="ended_at" :value="__('timesheet.ended_at')" />

                        <x-input id="ended_at" class="block mt-1 w-full"
                        type="dateTime-local"
                        name="ended_at"
                        value="{{ old('ended_at', date('Y-m-d\TH:m:s',  strtotime($timesheet->ended_at))) }}" />
                    </div>
                    <div>
                        <x-button>{{ __('customer.submit') }}</x-button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/timesheets/index.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Timesheet list') }}
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <div class="mb-5 mt-4">
                    <div class="flex flex-wrap justify-between">
                        <div class="md:w-1/2">
                            <x-table-search :search="$search"/>
                        </div>
                        <div class="md:w-1/2 text-right">
                            <x-table-create model="timesheets" />
                        </div>
                    </div>
                    <x-table-error />
                </div>
                <x-table>
                    <x-slot name="header">
                        <x-table-column>{{ __('Customer') }}</x-table-column>
                        <x-table-column>{{ __('Project') }}</x-table-column>
                        <x-table-column>{{ __('Description') }}</x-table-column>
                        <x-table-column>{{ __('Price type') }}</x-table-column>
                        <x-table-column>{{ __('Price') }}</x-table-column>
                        <x-table-column>{{ __('Started at') }}</x-table-column>
                        <x-table-column>{{ __('Ended at') }}</x-table-column>
                        <x-table-column>{{ __('Invoice') }}</x-table-column>
                        <x-table-column>{{ __('Action') }}</x-table-column>
                    </x-slot>
                    @forelse($timesheets as $row)
                        <tr>
                            <x-table-column><a href="{{ route('customers.show',$row->project->customer) }}" class="hover:underline">{{ $row->project->customer->name }}</a></x-table-column>
                            <x-table-column><a href="{{ route('projects.show',$row->project) }}" class="hover:underline">{{ $row->project->name }}</a></x-table-column>
                            <x-table-column>{{ $row->description ?? '-' }}</x-table-column>
                            <x-table-column>{{ $row->price_type->name ?? '-' }}</x-table-column><x-table-column><x-format-amount :amount="$row->price" currency="eur" locale="fr_BE" /></x-table-column>
                            <x-table-column>{{ $row->started_at ?? '-' }}</x-table-column>
                            <x-table-column>{{ $row->ended_at ?? '-' }}</x-table-column>
                            <x-table-column>{{ optional($row->invoice)->invoice_year ?? '-' }}{{ optional($row->invoice)->invoice_month ?? '-' }}{{ optional($row->invoice)->invoice_increment ?? '-' }}</x-table-column>
                            <x-table-column>
                                <x-table-action model="timesheets" :row="$row" :condition="$row->invoice"/>
                            </x-table-column>
                        </tr>
                    @empty
                        <tr>
                            <td class="px-4 py-2 border text-red-500" colspan="8">{{ __('No timesheets found.') }}</td>
                        </tr>
                    @endforelse
                    <x-slot name="pagination">
                        {{ $timesheets->links() }}    
                    </x-slot>
                </x-table>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/timesheets/show.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Show Timesheet') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('timesheets.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <table class="w-full table-fixed">
                    <tbody>
                        <tr>
                            <td class="px-4 py-2 font-bold">Company</td>
                            <td>{{ $timesheet->project->customer->name }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Project</td>
                            <td>{{ $timesheet->project->name }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Description</td>
                            <td>{{ $timesheet->description }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Price type</td>
                            <td>{{ $timesheet->price_type->name }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Started at</td>
                            <td>{{ $timesheet->started_at }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Ended at</td>
                            <td>{{ $timesheet->ended_at }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Created on</td>
                            <td>{{ date_format($timesheet->created_at, 'jS F Y g:i A') }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Last updated</td>
                            <td>{{ date_format($timesheet->updated_at, 'jS F Y g:i A') }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>