routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TimesheetController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Route::post('api/fetch-states', [DropdownController::class, 'fetchState']);
Route::post('api/fetch-cities', [DropdownController::class, 'fetchCity']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'customers'], function () {
        Route::resource('customers', CustomerController::class);
        Route::resource('contacts', ContactController::class);
        Route::resource('locations', LocationController::class);
    });
    Route::group(['prefix' => 'projects'], function () {
        Route::resource('projects', ProjectController::class);
        Route::resource('timesheets', TimesheetController::class);
        Route::resource('invoices', InvoiceController::class);
    });
});

require __DIR__ . '/auth.php';

app/Models/Invoice.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use App\Services\Invoice as ServicesInvoice;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Invoice extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'invoice_year',
        'invoice_month',
        'invoice_increment',
        'total_without_vat',
        'total_vat',
        'total_with_vat',
        'is_paid',
        'customer_id',
    ];

    protected $searchableFields = ['*'];

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    public function timesheets(): HasMany
    {
        return $this->hasMany(Timesheet::class);
    }

    public static function boot()
    {
        parent::boot();

        static::creating(function ($item) {
            $invoiceService = new ServicesInvoice();
            $customer = Customer::find($item->customer_id);
            $timesheets = $invoiceService->getTimesheets($customer, $item->invoice_year, $item->invoice_month);
            if ($timesheets) {
                $item->total_without_vat = $invoiceService->calculateTotalInvoice($timesheets);
                $item->total_vat = $invoiceService->calculateTotalVat($item->total_without_vat);
                $item->total_with_vat = $item->total_without_vat + $item->total_vat;
            }

            return $item;
        });

        static::created(function ($item) {
            $invoiceService = new ServicesInvoice();
            $customer = Customer::find($item->customer_id);
            $timesheets = $invoiceService->getTimesheets($customer, $item->invoice_year, $item->invoice_month);
            if ($timesheets) {
                $invoiceService->linkTimesheets($timesheets, $item);
            }
        });
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Invoice\StoreRequest;
use App\Http\Requests\Invoice\UpdateRequest;
use App\Models\Customer;
use App\Models\Invoice;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class InvoiceController extends Controller
{
    public function index(Request $request): View
    {
        $search = $request->get('search', '');

        $invoices = Invoice::search($search)
            ->latest()
            ->with('customer')
            ->withCount('timesheets')
            ->paginate(10);

        return view('invoices.index', compact('invoices', 'search'));
    }

    public function create(): View
    {
        $customers = Customer::pluck('name', 'id');

        return view('invoices.create', compact('customers'));
    }

    public function store(StoreRequest $request): RedirectResponse
    {
        Invoice::create($request->validated());

        return redirect()
            ->route('invoices.index')
            ->withSuccess('Invoice has been created successfully.');
    }

    public function show(Invoice $invoice): View
    {
        return view('invoices.show', compact('invoice'));
    }

    public function edit(Invoice $invoice): View
    {
        $customers = Customer::pluck('name', 'id');

        return view('invoices.edit', compact('customers', 'invoice'));
    }

    public function update(Invoice $invoice, UpdateRequest $request): RedirectResponse
    {
        $invoice->update($request->validated());

        return redirect()
            ->route('invoices.index')
            ->withSuccess('Invoice Has Been updated successfully');
    }

    public function destroy(Invoice $invoice): RedirectResponse
    {
        $invoice->delete();

        return redirect()
            ->route('invoices.index')
            ->withSuccess('Invoice has been deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/FormatAmount.php
<?php

namespace App\View\Components;

use Illuminate\Support\Str;
use Illuminate\View\Component;
use Money\Currencies\ISOCurrencies;
use Money\Currency;
use Money\Formatter\IntlMoneyFormatter;
use Money\Money;
use NumberFormatter;

class FormatAmount extends Component
{
    private $amount;
    private $currency;
    private $locale;

    public function __construct(int $amount, string $currency, ?string $locale = null)
    {
        $this->amount = $amount;
        $this->currency = $currency;
        $this->locale = $locale ?? app()->getLocale();
    }

    public function render()
    {
        $money = new Money($this->amount, new Currency(Str::upper($this->currency)));

        $numberFormatter = new NumberFormatter($this->locale, NumberFormatter::CURRENCY);
        $moneyFormatter = new IntlMoneyFormatter($numberFormatter, new ISOCurrencies());

        return $moneyFormatter->format($money);
    }
}

resources/views/invoices/create.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Create invoice') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('invoices.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form action="{{ route('invoices.store') }}" method="POST" >
                    @csrf
                    <div class="mb-4">
                        <x-label for="customer_id" :value="__('invoice.customer')" class="required" />

                        <select name="customer_id" id="customer_id" 
                        class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required>
                            <option disabled hidden {{ old('customer_id') != null ?: 'selected' }}>
                                {{ __('project.select') }}
                            </option>
                            @foreach($customers as $value => $label)
                                <option value="{{ $value }}" {{ old('customer_id') != $value ?: 'selected' }}>
                                    {{ $label }}
                                </option>
                            @endforeach
                        </select>
                    </div>    
                    <div class="mb-4">
                        <x-label for="invoice_year" :value="__('invoice.year')" class="required" />

                        <x-input id="invoice_year" class="block mt-1 w-full"
                        type="number"
                        name="invoice_year"
                        value="{{ old('invoice_year') }}" 
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="invoice_month" :value="__('invoice.month')" class="required" />

                        <x-input id="invoice_month" class="block mt-1 w-full"
                        type="number"
                        name="invoice_month"
                        value="{{ old('invoice_month') }}" 
                        required />
                    </div>
                    <div class="mb-4">
                        <x-label for="invoice_increment" :value="__('invoice.increment')" class="required" />

                        <x-input id="invoice_increment" class="block mt-1 w-full"
                        type="number"
                        name="invoice_increment"
                        value="{{ old('invoice_increment') }}" 
                        required />
                    </div>
                    <div>
                        <x-button>{{ __('customer.submit') }}</x-button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/invoices/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Edit invoice') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('invoices.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back </a>
                        <x-validation-errors class="mb-4" :errors="$errors" />
                        <form action="{{ route('invoices.update', $invoice) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-4">
                                <x-label for="customer_id" :value="__('invoice.customer')" class="required" />

                                <select name="customer_id" id="customer_id"
                                    class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                                    required>
                                    <option disabled hidden {{ old('customer_id') != null ?: 'selected' }}>
                                        {{ __('project.select') }}
                                    </option>
                                    @foreach ($customers as $value => $label)
                                        <option value="{{ $value }}"
                                            {{ old('customer_id', $invoice->customer->id) != $value ?: 'selected' }}>
                                            {{ $label }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-4">
                                <x-label for="invoice_year" :value="__('invoice.year')" class="required" />

                                <x-input id="invoice_year" class="block mt-1 w-full" type="number" name="invoice_year"
                                    value="{{ old('invoice_year', $invoice->invoice_year) }}" required />
                            </div>
                            <div class="mb-4">
                                <x-label for="invoice_month" :value="__('invoice.month')" class="required" />

                                <x-input id="invoice_month" class="block mt-1 w-full" type="number" name="invoice_month"
                                    value="{{ old('invoice_month', $invoice->invoice_month) }}" required />
                            </div>
                            <div class="mb-4">
                                <x-label for="invoice_increment" :value="__('invoice.increment')" class="required" />

                                <x-input id="invoice_increment" class="block mt-1 w-full" type="number"
                                    name="invoice_increment"
                                    value="{{ old('invoice_increment', $invoice->invoice_increment) }}" required />
                            </div>
                            <div class="mb-4">
                                <x-label for="is_paid" :value="__('invoice.is_paid')" class="required" />
                                <div class="flex justify-left">
                                    <div class="form-check form-check-inline">
                                        <input
                                            class="form-check-input form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                                            type="radio" name="is_paid" id="is_paid_no" value="0"
                                            {{ old('is_paid', $invoice->is_paid) != 0 ?: 'checked' }}>
                                        <label class="form-check-label inline-block text-gray-800"
                                            for="inlineRadio10">__('invoice.is_paid.no')</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input
                                            class="form-check-input form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                                            type="radio" name="is_paid" id="is_paid_yes" value="1"
                                            {{ old('is_paid', $invoice->is_paid) != 1 ?: 'checked' }}>
                                        <label class="form-check-label inline-block text-gray-800"
                                            for="inlineRadio20">__('invoice.is_paid.yes')</label>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <x-button>{{ __('invoice.submit') }}</x-button>
                            </div>
                        </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/invoices/index.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Invoices list') }}
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <div class="mb-5 mt-4">
                    <div class="flex flex-wrap justify-between">
                        <div class="md:w-1/2">
                            <x-table-search :search="$search"/>
                        </div>
                        <div class="md:w-1/2 text-right">
                            <x-table-create model="invoices" />
                        </div>
                    </div>
                    <x-table-error />
                </div>
                <x-table>
                    <x-slot name="header">
                        <x-table-column>{{ __('Customer') }}</x-table-column>
                        <x-table-column>{{ __('Date creation') }}</x-table-column>
                        <x-table-column>{{ __('Reference') }}</x-table-column>
                        <x-table-column>{{ __('Total Without VAT') }}</x-table-column>
                        <x-table-column>{{ __('Is paid ?') }}</x-table-column>
                        <x-table-column>{{ __('Action') }}</x-table-column>
                    </x-slot>
                    @forelse($invoices as $row)
                        <tr>
                            <x-table-column><a href="{{ route('customers.show',$row->customer) }}" class="hover:underline">{{ $row->customer->name }}</a></x-table-column>
                            <x-table-column>{{ $row->created_at }}</x-table-column>
                            <x-table-column>{{ $row->invoice_year }}{{ $row->invoice_month }}{{ $row->invoice_increment }}</x-table-column>
                            <x-table-column><x-format-amount :amount="$row->total_without_vat" currency="eur" locale="fr_BE" /> <span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-200 dark:text-green-900">{{ $row->timesheets_count }}</span></x-table-column>
                            <x-table-column>{{ $row->is_paid }}</x-table-column>
                            <x-table-column>
                                <x-table-action model="invoices" :row="$row" :condition="$row->is_paid"/>
                            </x-table-column>
                        </tr>
                    @empty 
                        <tr>
                            <td class="px-4 py-2 border text-red-500" colspan="6">{{ __('No invoices found.') }}</td>
                        </tr>
                    @endforelse
                    <x-slot name="pagination">
                        {{ $invoices->links() }}    
                    </x-slot>
                </x-table>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/invoices/show.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Show Invoice') }}
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">
                <a href="{{ route('invoices.index') }}"
                    class="inline-flex items-center px-4 py-2 mb-4 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-green-600 border border-transparent rounded-md hover:bg-green-500 active:bg-green-700 focus:outline-none focus:border-green-700 focus:shadow-outline-gray disabled:opacity-25">
                    <- Go back
                </a>
                <table class="w-full table-fixed">
                    <tbody>
                        <tr>
                            <td class="px-4 py-2 font-bold">Company</td>
                            <td>{{ $invoice->customer->name }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Year</td>
                            <td>{{ $invoice->invoice_year }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Month</td>
                            <td>{{ $invoice->invoice_month }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Increment</td>
                            <td>{{ $invoice->invoice_increment }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">price without VAT</td>
                            <td>{{ $invoice->total_without_vat }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">VAT</td>
                            <td>{{ $invoice->total_vat }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Price with VAT</td>
                            <td>{{ $invoice->total_with_vat }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Is Paid</td>
                            <td>{{ $invoice->is_paid }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Created on</td>
                            <td>{{ date_format($invoice->created_at, 'jS F Y g:i A') }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-2 font-bold">Last updated</td>
                            <td>{{ date_format($invoice->updated_at, 'jS F Y g:i A') }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>